name: crystal-video
channels: 
  - conda-forge
  - nodefaults
dependencies:
  - jupyterlab>=3
  - scikit-image
  - opencv
  - matplotlib
  - ipympl
  - tqdm
  - pytest
  - coverage
  - hypothesis
  # - mpl-interactions
  # - plotly
  # - ipywidgets >=7.6
  # - jupyter-dash